version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: solokuenstler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    ports:
      - 5432:5432

  openvidu:
    image: openvidu/openvidu-server-kms
    environment:
      openvidu.publicurl: https://openvidu:4443
      # Username: OPENVIDUAPP
      openvidu.secret: "MY_SECRET"
      spring.datasource.username: root
      spring.datasource.password: password
    ports:
      - 4443:4443

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - 9200:9200

  app:
    build: .
    environment:
      NODE_ENV: "development"
      OPENVIDU_USER: "OPENVIDUAPP"
      OPENVIDU_PASS: "MY_SECRET"
    command: ["bash", "./wait-for-it.sh", "postgres:5432", "--", "yarn", "run", "start"]
    volumes:
      - .:/app
    ports:
      - 80:3030
    depends_on:
      - openvidu
      - postgres
      - elasticsearch
    links:
      - openvidu
      - postgres
      - elasticsearch